version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Docker/python/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"